pretrained_model_path: "./ckpt/StdGEN-canonicalize-1024"

validation:
  guidance_scale: 5.0
  timestep: 40
  width_input: 640
  height_input: 1024
  use_inv_latent: False

use_noise: False
unet_condition_type: image

unet_from_pretrained_kwargs:
  camera_embedding_type: 'e_de_da_sincos'
  projection_class_embeddings_input_dim: 10  # modify
  joint_attention: false  # modify
  num_views: 1
  sample_size: 96
  zero_init_conv_in: false
  zero_init_camera_projection: false  
  in_channels: 4
  use_safetensors: true