model_config:
  target: slrm.models.lrm_mesh.MeshSLRM
  params:
    encoder_feat_dim: 768
    encoder_freeze: false
    encoder_model_name: facebook/dino-vitb16
    transformer_dim: 1024
    transformer_layers: 16
    transformer_heads: 16
    triplane_low_res: 32
    triplane_high_res: 64
    triplane_dim: 80
    rendering_samples_per_ray: 128
    grid_res_xy: 100
    grid_res_z: 150
    grid_scale_xy: 1.4
    grid_scale_z: 2.1
    is_ortho: false
    lora_rank: 128


infer_config:
  model_path: ckpt/StdGEN-mesh-slrm.pth
  texture_resolution: 1024
  render_resolution: 512